### ISSUE TITLE
[FR] 图片好像没有成功转换

### ISSUE THREAD

**Issue by Moyf** [msgk239/obsidian-copy-image-text#1]
过程如图：
![31b9c0a0-17dc-4bdc-b889-e431086c8c42](https://github.com/user-attachments/assets/29a71c0d-1197-4208-9df3-882ebecd1e54)

选中图片和文本，粘贴出来还是图片的链接。

选中文本的原文内容：
```md
emmm……图片转 base64 的话，可以更方便地发到公众号什么的？
那样能省下不少时间！

![[241112_十一月OB插件记录-img-241113_114528.jpg|400]]
```

**Comment by msgk239** [comment]
你用word试一下，或者直接在微信公众号上试。我测试是可以的。
好像是Sublime Text本身不能显示图片吧

**Comment by Moyf** [comment]
> 你用word试一下，或者直接在微信公众号上试。我测试是可以的。 好像是Sublime Text本身不能显示图片吧

唔，看来是和目标平台有关系……
我在 QQ 聊天框、Github 的回复框以及 OB 论坛的发布帖子界面都不行，Word 可以。

看了一下剪贴板内容，HTML 是写入了图片 B64 编码的，只是有些平台不会去读取它，只会读取纯文本内容  0~0
![image](https://github.com/user-attachments/assets/e5901595-b2d1-4713-8b5b-0eb23509f2fe)

总之我再尝试看看有没有什么办法让更多平台能吃到图片~ 感谢！
